### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by Sayanpal005** [Rajatendu1/Machine-Learning-Project-for-MindTree#2]
pre_data = gold_data[:]
pre_data_new = pre_data['new']
pre_data_new = pre_data_new.values.reshape(-1,1)
na_data = (regression_model.predict(pre_data_new))#getting predicted values
na_data_series = pd.Series(na_data.ravel())
sata = na_data_series.to_frame()
gold_data['Pred'] = sata
gold_data......
After running this why Pred is set as Nan in the table below in my case? i have done the same thing u shown above. please help me as early as possible...
![Screenshot (287)](https://user-images.githubusercontent.com/47541184/82988434-c733b200-a016-11ea-8327-6ba7ef4710c0.png)

**Comment by Rajatendu1** [comment]
Did you drop the Nan valued rows from the Gold.csv file before filling the pred column using your regressional model? Did you check your regression model if it is defined correctly? The regressional model you used in this cell has been defined in the previous cell. Also for training the model, the dataset without Nan values has been used. Check out my code , I am sure there's a problem in defining your model or the values you used for training the model.
