### ISSUE TITLE
Interview for ML Internship

### ISSUE THREAD

**Issue by skystone1000** [Rajatendu1/Machine-Learning-Project-for-MindTree#3]
Hi, I wanted to know how is the interview after the 6 modules, What are the question or the types of questions asked in the interview??
Thanks in advance

**Comment by Rajatendu1** [comment]
For me it was a recorded interview. You will be asked a data science
question by a automated bot. You will be asked to answer the question
within 30 secs to 1 minute.

After 5 questions your interview will be over.

No report was generated for my interview and my certificate was unlocked.

**Comment by skystone1000** [comment]
So in short the interview did not matter much? What were the type of questions and were they difficult??

**Comment by Sadique96645** [comment]
do we need to prepare the inference ?

**Comment by Rajatendu1** [comment]
Yes , in short it didn't matter. The questions were of intermediate level
and are to test whether you know the basic terms and conditions of data
science.

**Comment by Rajatendu1** [comment]
I did this internship a while back and didn't have to make any inference.

**Comment by skystone1000** [comment]
Ok thanks
